name: Dima

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-dima
    hostname: sql-server-dima
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!Admin123
    volumes:
      - ./mssql-data:/var/opt/mssql
    networks:
      - dima-net

networks:
  dima-net:
    driver: bridge
